### PR TITLE
feat: create onlyPKPOwner modifier

### PR DESCRIPTION
**Pull request by raymondfeng**
Signed-off-by: Raymond Feng <enjoyjava@gmail.com>

### CODE REVIEW

**Comment by raymondfeng** [comment]
Hmm, not sure why `npm run compile` fails:
```
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> contracts/PKPPermissions.sol:326:39:
    |
326 |             permittedAuthMethodScopes[tokenId][authMethodId].set(scopeId);
    |                                       ^^^^^^^


Error HH600: Compilation failed
```

**Comment by glitch003** [comment]
Did you get the stack too deep error fixed?  

The onlyPKPOwner modifier looks great!  And then you also set it up so that we are passing around the AuthMethod struct instead of the individual pieces, right?  

Anything else I should be looking at here?  

Thanks for getting these optimizations in @raymondfeng

**Comment by raymondfeng** [comment]
Yes, using struct fixed the issue.

**Comment by raymondfeng** [comment]
I’ll rebase this PR tmr

**Pull request merged**
